ALTER TABLE temp_orders
  ADD COLUMN IF NOT EXISTS gross DECIMAL(10,2) DEFAULT NULL COMMENT 'Total bruto sem frete',
  ADD COLUMN IF NOT EXISTS discount DECIMAL(10,2) DEFAULT NULL COMMENT 'Valor de desconto',
  ADD COLUMN IF NOT EXISTS total DECIMAL(10,2) DEFAULT NULL COMMENT 'Total final do pedido';
