CREATE TABLE IF NOT EXISTS temp_products (
  id INT(11) NOT NULL AUTO_INCREMENT,
  product_id BIGINT NOT NULL,
  title VARCHAR(500) DEFAULT NULL,
  is_active TINYINT(1) DEFAULT NULL,
  sku_id BIGINT DEFAULT NULL,
  sku_title VARCHAR(500) DEFAULT NULL,
  partner_id VARCHAR(255) DEFAULT NULL,
  ean VARCHAR(13) DEFAULT NULL,
  price DECIMAL(10,2) DEFAULT NULL,
  amount INT DEFAULT NULL,
  stock_local_id BIGINT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY unique_sku (product_id, sku_id),
  KEY idx_partner_id (partner_id),
  KEY idx_ean (ean)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
