CREATE TABLE IF NOT EXISTS temp_orders (
  id INT(11) NOT NULL AUTO_INCREMENT,
  order_id VARCHAR(255) DEFAULT NULL,
  marketplace_id VARCHAR(255) DEFAULT NULL,
  marketplace VARCHAR(255) DEFAULT NULL,
  status VARCHAR(50) DEFAULT NULL,
  fulfillment VARCHAR(50) DEFAULT NULL,
  created_at DATETIME DEFAULT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY order_id (order_id)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
