CREATE TABLE IF NOT EXISTS temp_products (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  produtoVarianteId BIGINT(20) NOT NULL,
  produtoId BIGINT(20) NOT NULL,
  idPaiExterno BIGINT(20) DEFAULT NULL,
  sku VARCHAR(191) NOT NULL,
  nome VARCHAR(500) NOT NULL,
  nomeProdutoPai VARCHAR(500) DEFAULT NULL,
  precoCusto DECIMAL(10,2) DEFAULT NULL,
  precoDe DECIMAL(10,2) DEFAULT NULL,
  precoPor DECIMAL(10,2) DEFAULT NULL,
  ean VARCHAR(100) DEFAULT NULL,
  centroDistribuicaoId INT(11) NOT NULL,
  estoqueFisico INT(11) NOT NULL,
  estoqueReservado INT(11) NOT NULL,
  alertaEstoque INT(11) NOT NULL,
  dataCriacao DATETIME DEFAULT NULL,
  dataAtualizacao DATETIME DEFAULT NULL,
  parentId BIGINT(20) DEFAULT NULL,
  raw_payload JSON NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_centroDistribuicaoId (centroDistribuicaoId),
  KEY idx_produtoVarianteId (produtoVarianteId),
  KEY idx_produtoId (produtoId),
  KEY idx_sku (sku)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
